name: pull
on:
  pull_request:
    branches:
      - master
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: e2e tests
      run: |
        npm run build
        npm run test:e2e:setup
        npm run test:e2e

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'connect e2e tests'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK }}
