name: pull
on:
  pull_request:
    branches:
      - master
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: e2e tests
      run: |
        npm run test:e2e

