name: pull
on:
  pull_request:
    branches:
      - master
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        test_suite: [unit, e2e]

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: ${{matrix.test_suite}} tests
      if: matrix.test_suite == 'e2e'
      run: |
        npm run build
        npm run test:e2e:setup
        npm run test:e2e
      if: matrix.test_suite == 'unit'
      run: npm run test:unit

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'connect ${{matrix.test_suite}} tests'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK }}
