<template>
  <form @submit.prevent="emitSubmit">
    <form-field>
      <message data-test="form-message"
        >Enter the 6 digit code generated by your authenticator app.</message
      >
    </form-field>
    <form-field v-if="error">
      <message :error="true" data-test="error-message">{{ error }}</message>
    </form-field>
    <form-field>
      <v-input
        v-model="code"
        :invalid="!isCodeValid"
        :autofocus="true"
        type="number"
        name="code"
        placeholder="Enter received code..."
        data-test="email-input"
      />
    </form-field>
    <form-controls>
      <v-button
        :disabled="!isCodeValid || loading"
        :submit="true"
        type="primary"
        data-test="submit-button"
      >
        {{ primaryButtonLabel }}
      </v-button>
    </form-controls>
  </form>
</template>

<script>
import VButton from '../VButton.vue';
import VInput from '../VInput.vue';
import Message from '../Message.vue';
import FormField from '../FormField.vue';
import FormControls from '../FormControls.vue';

export default {
  name: 'OtpForm',

  props: {
    loading: {
      type: Boolean,
      default: false,
    },

    error: {
      type: String,
      default: null,
    },
  },

  data: () => ({
    code: '',
  }),

  computed: {
    primaryButtonLabel() {
      return !this.loading ? 'Submit code' : 'Loading...';
    },

    isCodeValid() {
      return /^\d{6}$/.test(this.code);
    },
  },

  methods: {
    emitSubmit() {
      if (this.isCodeValid) {
        this.$emit('submit', this.code);
      }
    },
  },

  components: {
    VButton,
    VInput,
    Message,
    FormField,
    FormControls,
  },
};
</script>
